### ISSUE TITLE
Daemon for Work Execution

### ISSUE THREAD

**Issue by rvighne** [cs130-w21/1#1]
## Epic
A server that makes a machine part of the swarm.

## User Stories
- [] As someone who who wants to execute a task, I want the server to advertise itself so that I can send work to it.
- [] As someone who who wants to execute a task, I want to send work to this server so that I can get the results back.
- [] As someone who who wants to execute a task, I want this server to use a environment I specify when running tasks so that I don't need to tailor the config to each different daemon.
