### ISSUE TITLE
Client sends jobs to daemons

### ISSUE THREAD

**Issue by rvighne** [cs130-w21/1#12]
## User Story
As a developer, I would like the recipes and environment information to be sent to the daemon so that jobs can be run in parallel.

## Detailed Description
Given that the job sorting module (#50) has linearized the DAG of jobs along with an API to find jobs that can run in parallel, the client should send those jobs to the daemon using SSH.

## Tasks
- [ ] Establish an SSH tunnel to the daemon (accept all host keys, as authentication is not a primary concern for now).
- [ ] Send an execute request over the SSH channel and and asynchronously wait for the result.
- [ ] Record success or failure to the job sorting module, and to the user when the job sorter declares completion.
- [ ] Write unit tests.

## Acceptance Criteria
- [ ] Given a new daemon is discovered somehow, then the client opens a new SSH connection to it without prompting.
- [ ] Given a job is ready but not started and a known daemon is idle, then the job is sent to the daemon.
- [ ] Given all sub-tasks are finished, the user is notified.

## Estimated points
1
