### ISSUE TITLE
Daemon advertises itself

### ISSUE THREAD

**Issue by rvighne** [cs130-w21/1#13]
## User Story
As a developer, I want every daemon to advertise itself on the network so that I can discover it and send work to it.

## Detailed Description
Provide additional details and context.

## Tasks
- [x] Create a name unique on the LAN (or receive one from user).
- [x] Make server listen on random port if not given.
- [x] Publish service using Bonjour.
- [x] Un-publish service on clean exit of daemon.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

Estimated points: 2
