### ISSUE TITLE
Client discovers daemons

### ISSUE THREAD

**Issue by rvighne** [cs130-w21/1#17]
## User Story
As a developer, I would like the client to discover available daemons on the LAN so that I don't need to manually specify them.

## Detailed Description
Provide additional details and context.

## Tasks
- [x] Browse for services with Junknet's service name using Bonjour.
- [ ] Remove services once they're determined to be down via Bonjour.
- [ ] Remove discovered services once after a certain number of retries.

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

Estimated points: 2
