### ISSUE TITLE
Create UML Diagrams

### ISSUE THREAD

**Issue by alexzma** [cs130-w21/1#18]
## Epic
*This epic is for the development team; it's not user-focused.*

Create UML diagrams so the development of code can be more organized and efficient. It allows users to view the intended implementation of the program quickly and in a standardized form, so that work can proceed quickly, while the users can still agree on implementation.

## User Stories
- [x] Create Use Case Diagram #19
- [x] Create Activity Diagram #20
- [x] Create Class Diagram #21
- [x] Create Sequence Diagrams #22
- [x] Create State Machine Diagrams #23

**Comment by yashlala** [comment]
Part B submitted.
