### ISSUE TITLE
Web Monitoring Frontend

### ISSUE THREAD

**Issue by rvighne** [cs130-w21/1#2]
## Epic
Create a web UI that is associated with a daemon and displays information about tasks the daemon is currently running.

The primary user will be a system administrator who wants to visually see the execution of jobs on his or her machine.

- The user can see which tasks are currently running and on behalf of which client.
- The user can view the resources that are currently being used by tasks.
- The user can cancel running tasks to reclaim system resources.

## User Stories
- [ ] Resource usage monitoring #8
- [ ] Cancel sub-task running on daemon #9 
- [ ] Shut down daemon #10

**Comment by Rohanator9000** [comment]
We no longer plan to implement this.
