### ISSUE TITLE
Create Class Diagram

### ISSUE THREAD

**Issue by alexzma** [cs130-w21/1#21]
## User Story
As a member of the team, I would like to know the relations between the parts of the application so that I can know how changes in the part I'm working on would affect other parts.

## Detailed Description
Using the class diagram, team members should be able to see what classes are in the project, and how they are related to each other. Furthermore, team members should be able to know what they can do using that class.

## Tasks
 - [x] Daemon
 - [x] Client
 - [x] ZeroconfClient
 - [x] ZeroconfDaemon
 - [x] JobOrderer
 - [x] Makefile Parser
 - [x] CLI User Frontend
 - [x] Job

## Acceptance Criteria
- [x] Given a class, then a team member should know what data and functions it has.
- [x] Given a pair of entities, then a team member should know how they relate.
