### ISSUE TITLE
Create State Machine Diagrams

### ISSUE THREAD

**Issue by alexzma** [cs130-w21/1#23]
## User Story
As a member of the team, I would like to know the states of a single application component and the transitions between them so that I would know how that component should act in every scenario.

## Detailed Description
Provide additional details and context.

## Tasks
 - [x] Diagram for Job Orderer (1 point)
 - [x] Diagram for Daemon (1 point)

## Acceptance Criteria
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**
- [ ] Given **[Condition]**, then **[Expected Result]**

Estimated points: 2
