### ISSUE TITLE
Extract Job information from Makefile

### ISSUE THREAD

**Issue by yashlala** [cs130-w21/1#41]
## User Story 

As a Developer, I would like Junknet to interpret the provided Makefile and automatically collect the list of targets, their required build files, and their build scripts. 

## Acceptance Criteria

Given a Makefile, extract its pertinent dependency/build information.

## Tasks

- [ ] Run `make --trace` in a portable manner, and capture its output. 
- [x] Extract Target+ Dependency info
- [x] Format this info as a list of jobs to send to the Client. 

## Deliverable
The Client gets the tree of `Job`s from a Makefile.

# Estimated points
- @yashlala 1
- @Rohanator9000 1
