### ISSUE TITLE
Daemon Server SSH Connection

### ISSUE THREAD

**Issue by pjot726** [cs130-w21/1#55]
## User Story
As a developer, I the server to accept connection requests from the client and establish a SSH connection.

## Detailed Description
A SSH Server must be built into the Daemon so that it can handle connection requests and establish an SSH connection, which will later be used in communication between daemon and client.

## Tasks
- [x] Establish a SSH connection.
- [ ] Write integration tests.

## Acceptance Criteria
- [x] Given a connection request from a client, the daemon must accept it and establish a SSH connection.

## Estimated points
1
