### ISSUE TITLE
Set up volumes for Docker containers on Daemon

### ISSUE THREAD

**Issue by pjot726** [cs130-w21/1#56]
## User Story
As a developer, I would like the Daemon send files to the proper Docker containers for execution.

## Detailed Description
The daemon should send files (locally) to the right Docker container for execution.

## Tasks

- [ ] Send input files and commands to client-specified local Docker container.
- [ ] Write integration tests.

## Acceptance Criteria
- [ ] Given files, the client sends them and the correlated command to the correct local Docker container.

## Estimated points
1
