### ISSUE TITLE
Daemon Output via SSH

### ISSUE THREAD

**Issue by pjot726** [cs130-w21/1#57]
## User Story
As a developer, I would like the daemon to return the files and output streams from the Docker containers to the client via SSH.

## Detailed Description
Using the SSH server connection established in #55 , the Daemon should use a combination of SFTP and SSH to send output files and streams from the docker container which ran the commands specified by the client back to the client. 

## Tasks
- [ ] Find output files/streams in the local filesystem and send them to the client using SFTP.
- [ ] Write integration tests.

## Acceptance Criteria
- [ ] Given Docker container has returned output files/streams, store results in the local filesystem.
- [ ] Given a job has output files, then the daemon server sends them to the client via SFTP.

## Estimated points
3

**Comment by rvighne** [comment]
Closing as duplicate of #59
