### ISSUE TITLE
Daemon SSH Server

### ISSUE THREAD

**Issue by pjot726** [cs130-w21/1#58]
## User Story
As a **[Role]**, I would like **[Requirement]** so that **[Reason]**.

## Detailed Description
Provide additional details and context.

## Acceptance Criteria
- [x] Given a client, then establish a SSH connection. (#55)
- [ ] Given input/commands from the client, parse and send to Docker containers (#56)
- [ ] Given output from containers, then send to client via SSH (#57)
