### ISSUE TITLE
Client pushes inputs and pulls build artifacts from daemon

### ISSUE THREAD

**Issue by rvighne** [cs130-w21/1#59]
## User Story
As a developer, I would like the client to transparently make the inputs available to jobs when they're running remotely and transparently download the outputs, so that I can write Make-style recipes as if they are running locally.

## Detailed Description
Using the SSH tunnel already established for triggering jobs (#12), upload (before executing) and download (after executing) a tarball of the entire project. This is overkill, but keeps the initial implementation simple. The client drives the file transfers in both directions, so the client needs to know about all the files that are involved, while the server merely needs to store them for long enough.

## Tasks
- [ ] Find input files in the local filesystem and send them using SFTP.
- [ ] Download output files to the local filesystem using SFTP.
- [ ] Write integration tests.

## Acceptance Criteria
- [ ] Given a job has input files, then the client send the files to the daemon so it can work on them.
- [ ] Given a job has output files, then the client downloads them after the daemon has finished so the user can view them.

## Estimated points
3
