### ISSUE TITLE
Command line user input Interface

### ISSUE THREAD

**Issue by rvighne** [cs130-w21/1#7]
## User Story
As a developer, I would like to specify a Makefile and a Docker image so that the work can be sent to the worker machines.

## Detailed Description

As a user, I would like to be able to interact with the controller, and specify the work I would like done. 
I should be able to do so via a standard UNIX shell interface; ie. by passing options to the frontend. 

## Tasks

- [x] Create command line front end
- [ ] Pass the information to the rest of the controller. 
- [x] Write tests. 

## Acceptance Criteria

- [x] Given a command line invocation with options, store these arguments. 

# Estimated points
1
